replicaCount: 1

image:
  repository: asia-south1-docker.pkg.dev/authentic-genre-444610-p2/prod-bow-chat/prod-bow-chat
  tag: V_127
  pullPolicy: IfNotPresent

command: ["bundle", "exec", "sidekiq"]
args: []

env:
  RAILS_ENV: production
  WORKER: "true"

existingSecret: ""

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

database:
  host: MzQuNDcuMjAzLjIwNg==
  name: Ym93X2NoYXRfc3RhZ2U=
  password: c2RmOGo5N1l5aXQ2
  user: cG9zdGdyZXM=

redisUrl: cmVkaXM6Ly9yZWRpczo2Mzc5

secret_key_base: Ym9obml0ZWNo
~