apiVersion: v1
kind: Secret
type: Opaque
data:
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_PASSWORD: {{ .Values.database.password }}
  DATABASE_USER: {{ .Values.database.user }}
  REDIS_URL: {{ .Values.redisUrl }} 
  SECRET_KEY_BASE:  {{ .Values.secret_key_base }}
  RAILS_ENV: {{ .Values.env.RAILS_ENV | b64enc }}
metadata:
  name: {{ include "worker.fullname" . }}-secret
